#!/bin/vbash

set firewall ipv6 forward filter default-action 'accept'
set firewall ipv6 forward filter rule 1 action 'accept'
set firewall ipv6 forward filter rule 1 state established 'enable'
set firewall ipv6 forward filter rule 2 action 'accept'
set firewall ipv6 forward filter rule 2 state related 'enable'
set firewall ipv6 forward filter rule 101 action 'accept'
set firewall ipv6 forward filter rule 101 inbound-interface interface-group 'IG_containers'
set firewall ipv6 forward filter rule 101 outbound-interface interface-group 'IG_containers'
set firewall ipv6 forward filter rule 106 action 'drop'
set firewall ipv6 forward filter rule 106 description 'zone_containers default-action'
set firewall ipv6 forward filter rule 106 outbound-interface interface-group 'IG_containers'
set firewall ipv6 forward filter rule 111 action 'accept'
set firewall ipv6 forward filter rule 111 inbound-interface interface-group 'IG_guest'
set firewall ipv6 forward filter rule 111 outbound-interface interface-group 'IG_guest'
set firewall ipv6 forward filter rule 116 action 'drop'
set firewall ipv6 forward filter rule 116 description 'zone_guest default-action'
set firewall ipv6 forward filter rule 116 outbound-interface interface-group 'IG_guest'
set firewall ipv6 forward filter rule 121 action 'accept'
set firewall ipv6 forward filter rule 121 inbound-interface interface-group 'IG_iot'
set firewall ipv6 forward filter rule 121 outbound-interface interface-group 'IG_iot'
set firewall ipv6 forward filter rule 126 action 'drop'
set firewall ipv6 forward filter rule 126 description 'zone_iot default-action'
set firewall ipv6 forward filter rule 126 outbound-interface interface-group 'IG_iot'
set firewall ipv6 forward filter rule 131 action 'accept'
set firewall ipv6 forward filter rule 131 inbound-interface interface-group 'IG_lan'
set firewall ipv6 forward filter rule 131 outbound-interface interface-group 'IG_lan'
set firewall ipv6 forward filter rule 136 action 'drop'
set firewall ipv6 forward filter rule 136 description 'zone_lan default-action'
set firewall ipv6 forward filter rule 136 outbound-interface interface-group 'IG_lan'
set firewall ipv6 forward filter rule 141 action 'accept'
set firewall ipv6 forward filter rule 141 inbound-interface interface-group 'IG_servers'
set firewall ipv6 forward filter rule 141 outbound-interface interface-group 'IG_servers'
set firewall ipv6 forward filter rule 146 action 'drop'
set firewall ipv6 forward filter rule 146 description 'zone_servers default-action'
set firewall ipv6 forward filter rule 146 outbound-interface interface-group 'IG_servers'
set firewall ipv6 forward filter rule 151 action 'accept'
set firewall ipv6 forward filter rule 151 inbound-interface interface-group 'IG_trusted'
set firewall ipv6 forward filter rule 151 outbound-interface interface-group 'IG_trusted'
set firewall ipv6 forward filter rule 156 action 'drop'
set firewall ipv6 forward filter rule 156 description 'zone_trusted default-action'
set firewall ipv6 forward filter rule 156 outbound-interface interface-group 'IG_trusted'
set firewall ipv6 forward filter rule 161 action 'accept'
set firewall ipv6 forward filter rule 161 inbound-interface interface-group 'IG_video'
set firewall ipv6 forward filter rule 161 outbound-interface interface-group 'IG_video'
set firewall ipv6 forward filter rule 166 action 'drop'
set firewall ipv6 forward filter rule 166 description 'zone_video default-action'
set firewall ipv6 forward filter rule 166 outbound-interface interface-group 'IG_video'
set firewall ipv6 forward filter rule 171 action 'accept'
set firewall ipv6 forward filter rule 171 inbound-interface interface-group 'IG_wan'
set firewall ipv6 forward filter rule 171 outbound-interface interface-group 'IG_wan'
set firewall ipv6 forward filter rule 176 action 'drop'
set firewall ipv6 forward filter rule 176 description 'zone_wan default-action'
set firewall ipv6 forward filter rule 176 outbound-interface interface-group 'IG_wan'

set firewall ipv6 input filter default-action 'accept'
set firewall ipv6 input filter rule 1 action 'accept'
set firewall ipv6 input filter rule 1 state established 'enable'
set firewall ipv6 input filter rule 2 action 'accept'
set firewall ipv6 input filter rule 2 state related 'enable'
set firewall ipv6 input filter rule 101 action 'drop'

set firewall ipv6 output filter default-action 'accept'
set firewall ipv6 output filter rule 1 action 'accept'
set firewall ipv6 output filter rule 1 state established 'enable'
set firewall ipv6 output filter rule 2 action 'accept'
set firewall ipv6 output filter rule 2 state related 'enable'
set firewall ipv6 output filter rule 101 action 'drop'

# Ensure VyOS can talk to itself
set firewall ipv6 output filter rule 10 action accept
set firewall ipv6 output filter rule 10 source group address-group router-addresses-ipv6
set firewall ipv6 output filter rule 10 destination group address-group router-addresses-ipv6
set firewall ipv6 input  filter rule 10 action accept
set firewall ipv6 input  filter rule 10 source group address-group router-addresses-ipv6
set firewall ipv6 input  filter rule 10 destination group address-group router-addresses-ipv6
